name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Running `elm make` in Docker
      uses: ./ # Uses an action in the root directory
    #- name: Running 'elm make' in Docker
    #  uses: jorelali/elmsolitaire@v5
